plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'androidx.navigation.safeargs.kotlin'
}

android {
    compileSdkVersion build_versions.compile_sdk
    buildToolsVersion build_versions.build_tools

    defaultConfig {
        applicationId "com.ak.feastit"
        minSdkVersion build_versions.min_sdk
        targetSdkVersion build_versions.target_sdk
        versionCode build_versions.version_code
        versionName build_versions.version_name
        buildConfigField("String", "API_KEY", "\"${SPOONACULAR_KEY}\"")

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        kapt {
            arguments {
                arg("room.schemaLocation", "$projectDir/schemas")
            }
        }
    }

    buildTypes {
        debug {
            versionNameSuffix ".debug"
            resValue "string", "app_version", "${defaultConfig.versionName}${versionNameSuffix}"
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            resValue "string", "app_version", "${defaultConfig.versionName}"
        }
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation deps.kotlin.stdlib
    implementation deps.core_ktx
    implementation deps.app_compat
    implementation deps.material
    implementation deps.constraint_layout

    // Coroutines
    implementation deps.coroutines.core
    implementation deps.coroutines.android

    implementation deps.lifecycle.viewmodel_ktx
    implementation deps.lifecycle.livedata_ktx

//    navigation
    implementation deps.navigation.fragment_ktx
    implementation deps.navigation.ui_ktx

//    recyclerview for concat adapter
    implementation deps.recyclerview

    // Dagger Hilt
    implementation deps.hilt.hilt_android
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    kapt deps.hilt.hilt_android_compiler

    // DataStore
    implementation deps.data_store

//    retrofit
    implementation deps.retrofit.runtime
    implementation deps.okhttp_logging_interceptor
    implementation deps.retrofit.moshi
    implementation deps.retrofit.moshi_converter
    kapt deps.retrofit.moshi_codegen

//    glide
    implementation deps.glide.runtime
    kapt deps.glide.compiler

//    room
    implementation deps.room.runtime
    implementation deps.room.ktx
    kapt deps.room.compiler

    testImplementation deps.junit
    androidTestImplementation deps.atsl.ext_junit
    androidTestImplementation deps.espresso.core
}