package com.ak.feastit.utils

const val APP_TAG = "FeastIt"
const val DEFAULT_PAGE_SIZE = "30"

const val IMG_INGREDIENT_BASE_URL = "https://spoonacular.com/cdn/ingredients_100x100/"

// API Query Keys
const val QUERY_SEARCH = "query"
const val QUERY_NUMBER = "number"
const val QUERY_OFFSET = "offset"
const val QUERY_API_KEY = "apiKey"
const val QUERY_DIET = "diet"
const val QUERY_ADD_RECIPE_INFORMATION = "addRecipeInformation"
const val QUERY_FILL_INGREDIENTS = "fillIngredients"

const val API_PATH_ID = "recipeId"
const val API_COMPLEX_SEARCH_RECIPES = "recipes/complexSearch"
const val API_GET_RECIPE_ANALYSED_INSTRUCTION = "recipes/{${API_PATH_ID}}/analyzedInstructions"


const val FEAST_DB = "feast_db"
const val DB_RECIPE_TABLE = "recipes"
const val DB_INGREDIENT_TABLE = "recipe_ingredients"
const val DB_INSTRUCTION_TABLE = "recipe_instructions"
const val DB_TABLE_ID = "id"
const val DB_TABLE_COL_NAME = "name"
const val DB_TABLE_COL_SUMMARY = "summary"
const val DB_TABLE_COL_IMG = "img"
const val DB_TABLE_COL_SOURCE = "source"
const val DB_MY_RECIPE_BOOK = "is_fav"
const val DB_RECIPE_ID = "recipe_id"
const val DB_RECIPE_READY_IN_MIN = "ready_in_mins"
const val DB_RECIPE_SERVINGS = "servings"
const val DB_RECIPE_PRICE = "price_per_serving"
const val DB_RECIPE_SOURCE_NAME = "source_name"
const val DB_RECIPE_CUISINES = "cuisines"
const val DB_RECIPE_DISH_TYPES = "dish_types"
const val DB_RECIPE_DIETS = "diets"
const val DB_INGREDIENT_NAME = "ingredient_name"
const val DB_INGREDIENT_CONSISTENCY = "consistency"
const val DB_INGREDIENT_SPEC = "ingredient_spec"
const val DB_INGREDIENT_AMOUNT = "ingredient_amount"
const val DB_INGREDIENT_UNIT = "ingredient_unit"
const val DB_INGREDIENT_ID = "ingredient_id"
const val DB_STEP_ID = "step_id"
const val DB_STEP_NUMBER = "step_no"
const val DB_STEP_DESC = "step_desc"
const val DB_STEP_INGREDIENTS = "step_ingredients"
const val DB_STEP_EQUIPMENTS = "step_equipments"
