// Copyright 2025, Ashish Mohite and the Yum Byte project contributors
// License Name: <Actual name>
package com.mak.feastit.remote.dto

import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class RecipeDTO(
  val aggregateLikes: Int? = null,
  val analyzedInstructions: List<AnalyzedInstructionDTO>? = emptyList(),
  val cheap: Boolean? = null,
  val cookingMinutes: Int? = null,
  val creditsText: String? = null,
  val cuisines: List<String>? = emptyList(),
  val dairyFree: Boolean? = null,
  val diets: List<String>? = emptyList(),
  val dishTypes: List<String>? = emptyList(),
  val extendedIngredients: List<ExtendedIngredientDTO>? = emptyList(),
  val gaps: String? = null,
  val glutenFree: Boolean? = null,
  val healthScore: Double? = null,
  val id: Long,
  val image: String? = null,
  val imageType: String? = null,
  val license: String? = null,
  val likes: Int? = null,
  val lowFodmap: Boolean? = null,
  val missedIngredientCount: Int? = null,
  val missedIngredients: List<MissedIngredientDTO>? = emptyList(),
  val occasions: List<String?>? = emptyList(),
  val preparationMinutes: Int? = null,
  val pricePerServing: Double? = null,
  val readyInMinutes: Int? = null,
  val servings: Int? = null,
  val sourceName: String? = null,
  val sourceUrl: String? = null,
  val spoonacularScore: Double? = null,
  val spoonacularSourceUrl: String? = null,
  val summary: String? = null,
  val sustainable: Boolean? = null,
  val title: String,
  val unusedIngredients: List<Any?>? = emptyList(),
  val usedIngredientCount: Int? = null,
  val usedIngredients: List<Any?>? = emptyList(),
  val vegan: Boolean? = null,
  val vegetarian: Boolean? = null,
  val veryHealthy: Boolean? = null,
  val veryPopular: Boolean? = null,
  val weightWatcherSmartPoints: Int? = null,
)
